version: '3'

services:
  hanami_server:
    build: ./hanami_server
    command: bundle exec hanami server --host 0.0.0.0
    ports:
      - 2300:2300
    volumes:
      - $PWD:/app
    depends_on:
      - db
    env_file:
      - ./hanami_server/.env.development
    links:
      - db:db

  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: password
